server:
  address: 0.0.0.0
  port: 8080




spring:
  webflux:
    static-path-pattern: /static/**
  #  profiles:
  #    active: dev
  session:
    store-type: redis      # 使用 Redis 存储 Session
    redis:
      flush-mode: immediate  # 每次请求都立即刷新 Session
      namespace: webflux-session  # Redis 会话命名空间
  autoconfigure:
    exclude:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  flyway:
    enabled: false
    locations:
      - classpath:db/migration
    cleanDisabled: false
    url: jdbc:mysql://101.34.152.79:3305/yoohoo-oauth?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    password: wwwwww
    user: root
    baseline-on-migrate: true

  jackson:
    time-zone: GMT+8
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    cache: false
    mode: HTML
  r2dbc:
    url: r2dbc:mysql://101.34.152.79:3305/yoohoo-oauth
    username: root
    password: wwwwww
    pool:
      initial-size: 5
      max-size: 20
  data:
    redis:
      port: 6378
      database: 0
      host: 101.34.152.79
      password: 123456


springdoc:
  swagger-ui:
    default-model-expand-depth: 3
  api-docs:
    path: /api-docs

aliyun:
  oss:
    accessKeyId: ${OSS_ACCESS_KEY_ID:default_access_key_id}
    accessKeySecret: ${OSS_ACCESS_KEY_SECRET:default_access_key_secret}





logging:
  level:
    org:
      springframework:
        security: DEBUG
        r2dbc: DEBUG
        web:
          server:
            reactive: DEBUG
            session: DEBUG



