server:
  address: 0.0.0.0
  port: 8080




spring:
  profiles:
    active: local
  security:
    user:
      enabled: false
  webflux:
    static-path-pattern: /static/**
  session:
    store-type: redis      # 使用 Redis 存储 Session
    redis:
      flush-mode: immediate  # 每次请求都立即刷新 Session
      namespace: webflux-session  # Redis 会话命名空间
  autoconfigure:
    exclude:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  flyway:
    enabled: false
    locations:
      - classpath:db/migration
    cleanDisabled: false
    url: jdbc:mysql://${custom-config.mysql.host}:${custom-config.mysql.port}/${custom-config.mysql.database}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    password: ${custom-config.mysql.password}
    baseline-on-migrate: true
    user: ${custom-config.mysql.username}

  jackson:
    time-zone: GMT+8
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    cache: false
    mode: HTML
  r2dbc:
    url: r2dbc:mysql://${custom-config.mysql.host}:${custom-config.mysql.port}/${custom-config.mysql.database}
    username: ${custom-config.mysql.username}
    password: ${custom-config.mysql.password}
    pool:
      max-size: 20                  # 最大连接数
      initial-size: 10              # 初始连接数
      max-idle-time: 30m            # 连接最大空闲时间
      validation-query: SELECT 1    # 连接验证查询
      validation-interval: 5000     # 验证间隔（单位毫秒）
  data:
    redis:
      port: ${custom-config.redis.port}
      database: ${custom-config.redis.database}
      host: ${custom-config.redis.host}
      password: ${custom-config.redis.password}
      repositories:
        enabled: false


springdoc:
  swagger-ui:
    default-model-expand-depth: 3
  api-docs:
    path: /api-docs









